<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{0aa57708-3cf4-4eb6-950e-a14cb0a5b886}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
// TcpIp sample PRG for client to server
PRG_TcpIP_ClientServer();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>